env: dev

replicas: 1


rollingUpdate:
  maxSurge: 1
  maxUnavailable: 0

PodDisruptionBudget:
  minAvailable: 50%

resources:
  memLimit: 750Mi
  cpuRequest: 650m
  memRequest: 500Mi

image:
  identifier: <+artifacts.primary.image>
  imagePullPolicy: Always
secondaryImage:
  identifier: eu.gcr.io/entur-system-1287/es-static:master-v26-8908900a
  imagePullPolicy: Always
  containerPort: 9200
  resources:
    memLimit: 2000Mi
    cpuRequest: 1200m
    memRequest: 1500Mi

service:
  http:
    externalPort: 80
    internalPort: 3000

horizontalPodAutoscaler:
  maxReplicas: 2
  minReplicas: 1
  targetCPUUtilizationPercentage: 80
