name: ci

on:
  push:
    branches:
      - main
      - master
      - dev
  pull_request_target:
    branches:
      - main
      - master
      - dev

permissions:
  checks: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node: [16, 17]

    steps:
      - name: Check out repository (push)
        if: ${{ github.event_name == 'push' || github.event_name == 'pull_request_target' || github.event_name == 'pull_request' && github.actor != 'dependabot[bot]' }}
        uses: actions/checkout@v2

      - name: Check out repository (pull_request_target)
        if: ${{ github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]' }}
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup node env 📦
        uses: actions/setup-node@v2.5.1
        with:
          node-version: ${{ matrix.node }}
          check-latest: true
          registry-url: https://registry.npmjs.org
          cache: 'npm'

      - name: Upgrade npm ✨
        run: npm i -g npm@latest

      - name: Install dependencies 🚀
        run: npm ci --prefer-offline --no-audit

      - name: Run linter(s) 👀
        uses: wearerequired/lint-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          git_name: github-actions[bot]
          git_email: github-actions[bot]@users.noreply.github.com
          continue_on_error: false
          auto_fix: true
          neutral_check_on_warning: true
          eslint: true
          eslint_extensions: js,ts
          prettier: true
          prettier_extensions: js,ts
